name: plc-utils
version: 0.1.0.0
license: MIT
github: "HachiSecurity/plc-utils"
author: "Michael B. Gale"
maintainer: "michael.gale@tweag.io"

dependencies:
  - base
  - bytestring
  - data-fix
  - flat
  - mtl
  - plutus-core
  - some
  - text

default-extensions:
  - ImportQualifiedPost

ghc-options:
  - -Wall
  - -Werror=missing-fields
  - -Werror=missing-methods

library:
  source-dirs: src
