name: build

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build.yml'
      - "src/**"
      - "*.cabal"
      - "stack*.yaml"
      - "package.yaml"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install system packages
        run: sudo apt -y update && sudo apt -y install libsodium-dev

      - name: Install Haskell
        id: "install-haskell"
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "8.10.7"
          enable-stack: true
          stack-version: "latest"

      - name: Cache .stack
        uses: actions/cache@v2
        with:
          path: ${{ steps.install-haskell.outputs.stack-root }}
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('plc-utils.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          stack --no-terminal build --only-dependencies --test --fast --system-ghc

      - name: Compile sources
        run: |
          stack --no-terminal build --test --fast --system-ghc --no-run-tests
